### PR TITLE
Some fixes to relative path handling

### LINKED ISSUE #274: componentsuite test fails with nil ref error trying to parse relative paths
When trying to test component builder with relative paths, 
```yaml
apiVersion: bundle.gke.io/v1alpha1
kind: ComponentBuilder
componentName: my-component
version: 0.0.1
appVersion: 0.0.1
objectFiles:
- url: dir/file.yaml
```

Inliner.objectFiles() fails [here](https://github.com/GoogleCloudPlatform/k8s-cluster-bundle/blob/master/pkg/build/inline.go#L204), then
nil ref is that error is ignored [here](https://github.com/GoogleCloudPlatform/k8s-cluster-bundle/blob/master/pkg/testutil/componentsuite/componentsuite.go#L76):
```
comp, err = inliner.ComponentFiles(ctx, bw.ComponentBuilder(), ts.ComponentFile)
		if err != nil {
		}
```
CC @Kashomon

### PR DESCRIPTION
**Pull request by Kashomon**
Now, in bundleio, make the component / bundle files absolute as soon as
possible and return an error in the inliner if they are not absolute.

Also: Fix relative path issues in component testsuite

Fixes:#279
Fixes #274

### CODE REVIEW

File: pkg/build/inline.go [hunk 1]
```diff
@@ -64,19 +65,29 @@ func NewInlinerWithScheme(scheme files.URLScheme, objReader files.FileObjReader)
...
-// BundleFiles converts dereferences file-references in for bundle files.
+// BundleFiles converts dereferences file-references in for bundle files. If
+// the bundlePath is defined and not absolute and the scheme is file based
+// scheme, then the path is made absolute before proceeding.
 func (n *Inliner) BundleFiles(ctx context.Context, data *bundle.BundleBuilder, bundlePath string) (*bundle.Bundle, error) {
 	bundleURL, err := url.Parse(bundlePath)
 	if err != nil {
 		return nil, err
 	}
+	bundleURL, err = n.PathRewriter.Abs(bundleURL)
```
Comment (BradfordMedeiros) [inline pkg/build/inline.go]: why is path rewriter a struct member as opposed to just a plain old function?

File: pkg/build/path_rewriter.go [hunk 2]
```diff
@@ -22,23 +22,20 @@ import (
 // RelativePathRewriter rewrites paths when the paths are relative paths.
 type RelativePathRewriter struct{}
 
-// MakeAbs rewrites file paths if the path is relative, from the
+// AbsWithParent rewrites file paths if the path is relative, from the
```
Comment (BradfordMedeiros) [inline pkg/build/path_rewriter.go]: This whole file should just be plain vanilla functions.  You then have to instance this and struct shove.  That can be avoided.

File: pkg/build/path_rewriter.go [hunk 3]
```diff
@@ -49,5 +46,23 @@ func (rw *RelativePathRewriter) MakeAbs(parent, obj *url.URL) *url.URL {
 	}
 }
 
+// Abs makes an absolute url for URL that has an empty or file-based
+// scheme.
+func (rw *RelativePathRewriter) Abs(obj *url.URL) (*url.URL, error) {
+	npath := obj.Path
+	if (obj.Scheme == "file" || obj.Scheme == "") && !filepath.IsAbs(obj.Path) {
```
Comment (BradfordMedeiros) [inline pkg/build/path_rewriter.go]: consider obj.Scheme = " dlfjkjasd;lkfjas"

This function returns nil error.

File: pkg/build/path_rewriter.go [hunk 4]
```diff
@@ -22,23 +22,20 @@ import (
...
 		return obj
 	}
 	if parent.Scheme != "file" && parent.Scheme != "" {
 		// Only file schemes are supported.
 		return obj
 	}
-	if !filepath.IsAbs(parent.Path) {
-		return obj
-	}
 	if filepath.IsAbs(obj.Path) {
```
Comment (BradfordMedeiros) [inline pkg/build/path_rewriter.go]: Function has behavior of returning the objpath is it's already absolute, disregarding the parent argument.

File: pkg/build/path_rewriter.go [hunk 5]
```diff
@@ -49,5 +46,23 @@ func (rw *RelativePathRewriter) MakeAbs(parent, obj *url.URL) *url.URL {
 	}
 }
 
+// Abs makes an absolute url for URL that has an empty or file-based
+// scheme.
+func (rw *RelativePathRewriter) Abs(obj *url.URL) (*url.URL, error) {
```
Comment (BradfordMedeiros) [inline pkg/build/path_rewriter.go]: pass by value as a default would be nicer so I can tell there's no mutation going on.

Comment (Kashomon) [reply pkg/build/path_rewriter.go]: you mean url.URL?

Technically go is always pass by value since references are themselves copied. https://dave.cheney.net/2017/04/29/there-is-no-pass-by-reference-in-go

File: pkg/build/path_rewriter.go (hunk 3 above)
Comment (Kashomon) [reply pkg/build/path_rewriter.go]: That seems fine to me. This doesn't care about unknown schemes. But, I would think that URL parsing would fail earlier

Comment (BradfordMedeiros) [reply pkg/build/path_rewriter.go]: this function needs to work on its own, you shouldn't depend on other functions behavior.  just rewrite it so the unknown defaults to an error instead of nil error.

File: pkg/build/path_rewriter.go (hunk 5 above)
Comment (BradfordMedeiros) [reply pkg/build/path_rewriter.go]: obj is a pointer.   It looks like you're not mutating obj. 
It would be clearer to not pass a pointer, so I know you're not mutating the value of obj. 

Not a big deal.

File: pkg/build/inline.go (hunk 1 above)
Comment (Kashomon) [reply pkg/build/inline.go]: Made a POF

File: pkg/build/path_rewriter.go (hunk 2 above)
Comment (Kashomon) [reply pkg/build/path_rewriter.go]: Done

File: pkg/build/path_rewriter.go (hunk 5 above)
Comment (Kashomon) [reply pkg/build/path_rewriter.go]: Ack

File: pkg/build/path_rewriter.go (hunk 4 above)
Comment (Kashomon) [reply pkg/build/path_rewriter.go]: Yes, that seems like the right behavior. If the path is already absolute, then it doesn't need to be made absolute

File: pkg/build/path_rewriter.go (hunk 3 above)
Comment (Kashomon) [reply pkg/build/path_rewriter.go]: Not following -- this makes it much cleaner. Here, Abs ignores all schemes it doesn't know about. I can add the checks here or in the parent file, but it's not clear to me which is better -- in the parent it adds duplication. 

I've changed the name to makeAbsForFileScheme to be clearer.

File: pkg/build/inline.go [hunk 6]
```diff
@@ -59,24 +57,32 @@ func NewInlinerWithScheme(scheme files.URLScheme, objReader files.FileObjReader)
...
 	}
 	return &Inliner{
-		Readers:      rdrMap,
-		PathRewriter: DefaultPathRewriter,
+		Readers: rdrMap,
 	}
 }
 
-// BundleFiles converts dereferences file-references in for bundle files.
+// BundleFiles converts dereferences file-references in for bundle files. If
```
Comment (justinsb) [inline pkg/build/inline.go]: Not really sure what "converts dereferences" means - typo?

File: pkg/build/inline.go [hunk 7]
```diff
@@ -205,11 +220,11 @@ func (n *Inliner) objectFiles(ctx context.Context, objFiles []bundle.File, ref b
 		if err != nil {
 			return nil, nil, err
 		}
-		cf.URL = n.PathRewriter.MakeAbs(componentPath, furl).String()
+		cf.URL = makeAbsWithParent(componentPath, furl).String()
 
 		contents, err := n.readFile(ctx, cf)
 		if err != nil {
-			return nil, nil, fmt.Errorf("error reading file %v for component %v: %v", cf, ref, err)
+			return nil, nil, fmt.Errorf("reading file %v for component %v: %v", cf, ref, err)
```
Comment (justinsb) [inline pkg/build/inline.go]: I think the old form (with "error reading...") was more go.

**Comment by justinsb** [comment]
Two non-code nits, but otherwise LGTM.  Going to pull it down & test it out (but if you've already done so, feel free to merge when you're happy)!

File: pkg/build/inline.go (hunk 7 above)
Comment (Kashomon) [reply pkg/build/inline.go]: Done

File: pkg/build/inline.go (hunk 6 above)
Comment (Kashomon) [reply pkg/build/inline.go]: Done
